"""Pydantic models for YAML spec validation."""

from typing import Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, model_validator


class S3Spec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["s3"]
    name: str
    versioning: bool = False
    # Secure-by-default; set false to omit the block.
    encryption: bool = True  # SSE-S3 (AES256) default encryption
    public_access_block: bool = True  # block all public access
    # Expire objects after N days; omit for no lifecycle rule.
    lifecycle_expiration_days: int | None = None


class InlinePolicy(BaseModel):
    """An inline allow policy for project-scoped access (e.g. a specific S3 bucket)."""

    model_config = ConfigDict(extra="forbid")

    name: str
    actions: list[str]
    resources: list[str]


class IAMRoleSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["iam_role"]
    name: str
    service: str
    policies: list[str] = []  # managed policy ARNs to attach
    inline_policies: list[InlinePolicy] = []  # scoped allow policies (S3/model access)


class ECRSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["ecr"]
    name: str
    scan_on_push: bool = True
    image_tag_mutability: Literal["MUTABLE", "IMMUTABLE"] = "MUTABLE"
    lambda_access: bool = False
    # Keep only the most recent N images; omit for no lifecycle policy.
    lifecycle_keep_last: int | None = None


class LambdaSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["lambda"]
    name: str
    role: str
    runtime: str | None = None
    handler: str | None = None
    memory: int = 128
    timeout: int = 3
    image_uri: str | None = None
    ecr_repo: str | None = None  # logical name of an ecr resource; generates a TF reference
    environment: dict[str, str] = {}
    # Expose the function over HTTPS via a Lambda function URL (opt-in).
    function_url: bool = False
    # Auth for the function URL; AWS_IAM (SigV4) by default, "NONE" for a public endpoint.
    function_url_auth: Literal["AWS_IAM", "NONE"] = "AWS_IAM"
    # Retention for the function's CloudWatch log group; omit for default (never expire).
    log_retention_days: int | None = None

    @model_validator(mode="after")
    def _validate_package_type(self) -> "LambdaSpec":
        is_image = self.image_uri is not None or self.ecr_repo is not None
        is_zip = self.runtime is not None or self.handler is not None
        if is_image and is_zip:
            raise ValueError(
                "Lambda cannot mix image fields (image_uri/ecr_repo) with zip fields "
                "(runtime/handler) — choose one package type."
            )
        if not is_image and not is_zip:
            raise ValueError(
                "Lambda must specify either image fields (image_uri or ecr_repo) "
                "or zip fields (runtime and handler)."
            )
        if is_zip and (self.runtime is None or self.handler is None):
            raise ValueError("Zip Lambda requires both runtime and handler.")
        return self


class RDSSpec(BaseModel):
    """A managed Postgres instance — e.g. the MLflow backend store that makes
    registry champions persist across runs (see docs/decisions/mlflow-tracking-backend.md).

    The master password is created and rotated by RDS in AWS Secrets Manager
    (``manage_master_user_password``) — it is never rendered into Terraform config
    or state. The generated ``<name>_master_user_secret_arn`` output is the ARN to
    wire into a project's ``secrets:`` manifest.
    """

    model_config = ConfigDict(extra="forbid")

    type: Literal["rds"]
    name: str
    engine_version: str = "16"  # Postgres major version
    instance_class: str = "db.t4g.micro"
    allocated_storage: int = 20  # GB
    backup_retention_days: int = 7  # automated backups / point-in-time recovery window
    db_name: str = "mlflow"  # the database created on the instance
    username: str = "mlflow"  # master username
    storage_encrypted: bool = True  # secure-by-default; encrypt at rest
    multi_az: bool = False
    publicly_accessible: bool = False  # secure-by-default; reach via VPC/SG
    deletion_protection: bool = True  # protect the champion store from accidental destroy
    skip_final_snapshot: bool = True  # no final snapshot on destroy (set false for prod retention)
    db_subnet_group_name: str | None = None  # existing subnet group (not generated by recipes)
    security_groups: list[str] = []  # logical names of security_group resources; generate TF refs
    vpc_security_group_ids: list[str] = []  # existing (literal) security group IDs


class IngressRule(BaseModel):
    """A single inbound rule on a security group."""

    model_config = ConfigDict(extra="forbid")

    port: int
    protocol: str = "tcp"
    cidr_blocks: list[str] = ["0.0.0.0/0"]
    description: str | None = None


def _default_ingress() -> list[IngressRule]:
    # Postgres-by-default: the common case is fronting an `rds` MLflow backend store.
    return [IngressRule(port=5432, description="PostgreSQL")]


class SecurityGroupSpec(BaseModel):
    """A security group — typically the inbound rule that makes an `rds` instance
    reachable (default: Postgres 5432). Attach it from an `rds` resource via
    ``security_groups: [<this name>]``.

    The default ingress CIDR is ``0.0.0.0/0`` (reachable from anywhere, e.g.
    GitHub-hosted CI runners with dynamic IPs) — pair it with TLS and the
    RDS-managed password, or narrow ``cidr_blocks`` to known ranges.
    """

    model_config = ConfigDict(extra="forbid")

    type: Literal["security_group"]
    name: str
    description: str = "Managed by recipes"
    vpc_id: str | None = None  # omit to use the account's default VPC
    ingress: list[IngressRule] = Field(default_factory=_default_ingress)
    egress_all: bool = True  # allow all outbound (standard for an egress-only client)


ResourceSpec = Annotated[
    Union[S3Spec, IAMRoleSpec, ECRSpec, LambdaSpec, RDSSpec, SecurityGroupSpec],
    Field(discriminator="type"),
]


class RecipeSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    region: str = "us-east-1"
    resources: list[ResourceSpec] = []

    @model_validator(mode="after")
    def _validate_resource_references(self) -> "RecipeSpec":
        iam_names = {r.name for r in self.resources if isinstance(r, IAMRoleSpec)}
        ecr_names = {r.name for r in self.resources if isinstance(r, ECRSpec)}
        sg_names = {r.name for r in self.resources if isinstance(r, SecurityGroupSpec)}
        errors: list[str] = []
        for r in self.resources:
            # rds.security_groups must each match a security_group resource in this spec
            if isinstance(r, RDSSpec):
                for sg in r.security_groups:
                    if sg not in sg_names:
                        errors.append(
                            f"RDS '{r.name}': security_group '{sg}' does not match any "
                            "security_group resource in this spec."
                        )
                continue
            if not isinstance(r, LambdaSpec):
                continue
            # role must be an existing iam_role name or a literal ARN
            if r.role not in iam_names and not r.role.startswith("arn:"):
                errors.append(
                    f"Lambda '{r.name}': role '{r.role}' does not match any iam_role "
                    "resource in this spec (and is not an ARN)."
                )
            # ecr_repo must be an existing ecr name
            if r.ecr_repo is not None and r.ecr_repo not in ecr_names:
                errors.append(
                    f"Lambda '{r.name}': ecr_repo '{r.ecr_repo}' does not match any "
                    "ecr resource in this spec."
                )
        if errors:
            raise ValueError("\n".join(errors))
        return self
